### ISSUE TITLE
"Validation failed"

### ISSUE THREAD

**Issue by fronbasal** [mriedmann/humhub-docker#34]
Hello! I am trying to set up this container with the provided docker-compose file in the repository.
I am getting the error "Validation Failed" from the humhub container.
Stacktrace:
```
humhub_1  | db (172.18.0.2:3306) open
humhub_1  | Creating database...
humhub_1  | PHP Warning:  Invalid argument supplied for foreach() in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 123
humhub_1  | Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'
humhub_1  |
humhub_1  | in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php:584
humhub_1  |
humhub_1  | Stack trace:
humhub_1  | #0 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php(928): yii\db\Connection->open()
humhub_1  | #1 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php(915): yii\db\Connection->getMasterPdo()
humhub_1  | #2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
humhub_1  | #3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(910): yii\db\Command->prepare(true)
humhub_1  | #4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(405): yii\db\Command->queryInternal('fetchAll', 7)
humhub_1  | #5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(352): yii\db\Command->queryColumn()
humhub_1  | #6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Schema.php(234): yii\db\mysql\Schema->findTableNames('')
humhub_1  | #7 /var/www/localhost/htdocs/protected/humhub/components/console/Application.php(87): yii\db\Schema->getTableNames()
humhub_1  | #8 /var/www/localhost/htdocs/protected/humhub/components/console/Application.php(38): humhub\components\console\Application->isDatabaseInstalled()
humhub_1  | #9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\components\console\Application->init()
humhub_1  | #10 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
humhub_1  | #11 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
humhub_1  | #12 /var/www/localhost/htdocs/protected/yii(28): yii\console\Application->__construct(Array)
humhub_1  | #13 {main}
humhub_1  | Installing...
humhub_1  | PHP Warning:  Invalid argument supplied for foreach() in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 123
humhub_1  | Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'
humhub_1  |
humhub_1  | in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php:584
humhub_1  |
humhub_1  | Stack trace:
humhub_1  | #0 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php(928): yii\db\Connection->open()
humhub_1  | #1 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php(915): yii\db\Connection->getMasterPdo()
humhub_1  | #2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
humhub_1  | #3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(910): yii\db\Command->prepare(true)
humhub_1  | #4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(405): yii\db\Command->queryInternal('fetchAll', 7)
humhub_1  | #5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(352): yii\db\Command->queryColumn()
humhub_1  | #6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Schema.php(234): yii\db\mysql\Schema->findTableNames('')
humhub_1  | #7 /var/www/localhost/htdocs/protected/humhub/components/console/Application.php(87): yii\db\Schema->getTableNames()
humhub_1  | #8 /var/www/localhost/htdocs/protected/humhub/components/console/Application.php(38): humhub\components\console\Application->isDatabaseInstalled()
humhub_1  | #9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\components\console\Application->init()
humhub_1  | #10 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
humhub_1  | #11 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
humhub_1  | #12 /var/www/localhost/htdocs/protected/yii(28): yii\console\Application->__construct(Array)
humhub_1  | #13 {main}
humhub_1  | Config preprocessing ...
humhub_1  | PHP Warning:  Invalid argument supplied for foreach() in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 123
humhub_1  | Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'
humhub_1  |
humhub_1  | in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php:584
humhub_1  |
humhub_1  | Stack trace:
humhub_1  | #0 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php(928): yii\db\Connection->open()
humhub_1  | #1 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Connection.php(915): yii\db\Connection->getMasterPdo()
humhub_1  | #2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(219): yii\db\Connection->getSlavePdo()
humhub_1  | #3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(910): yii\db\Command->prepare(true)
humhub_1  | #4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Command.php(405): yii\db\Command->queryInternal('fetchAll', 7)
humhub_1  | #5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/mysql/Schema.php(352): yii\db\Command->queryColumn()
humhub_1  | #6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/db/Schema.php(234): yii\db\mysql\Schema->findTableNames('')
humhub_1  | #7 /var/www/localhost/htdocs/protected/humhub/components/console/Application.php(87): yii\db\Schema->getTableNames()
humhub_1  | #8 /var/www/localhost/htdocs/protected/humhub/components/console/Application.php(38): humhub\components\console\Application->isDatabaseInstalled()
humhub_1  | #9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\components\console\Application->init()
humhub_1  | #10 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
humhub_1  | #11 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
humhub_1  | #12 /var/www/localhost/htdocs/protected/yii(28): yii\console\Application->__construct(Array)
humhub_1  | #13 {main}
humhub_1  | validation failed!
humhub-docker_humhub_1 exited with code 1
```

Thanks!

**Comment by mriedmann** [comment]
Hello! Thank you for your report. 

Could you please post your docker-compose.yml file?

If you used the code from the readme-text please try to add the following environment-variables (see https://github.com/mriedmann/humhub-docker/blob/master/docker-compose.yml for details) 
```
HUMHUB_DB_USER: <dbuser>
HUMHUB_DB_PASSWORD: <dbpassword>
```

Thanks!

**Comment by fronbasal** [comment]
Hey! I am going to set up this environment some other time, sorry. I am attempting to install humhub manually. Thank you for your comment.
