### ISSUE TITLE
latest version?

### ISSUE THREAD

**Issue by punkyard** [mriedmann/humhub-docker#343]
hi
is the read_me page up to date? because it says latest version is 1.14

but when I installed humhub with docker, I got 1.15.0 and there is no mention of this version on the main page ..

I can see the 1.15.2 tag on docker hub - but it fails irremediably - also 1.15.1 - I have to go back to 1.15.0 to bring humhub back online

**Comment by punkyard** [comment]
I get these logs with 'latest' tag:

`    self.runforever()
  File "/usr/lib/python3.11/site-packages/supervisor/supervisord.py", line 244, in runforever
    self.reap()
  File "/usr/lib/python3.11/site-packages/supervisor/supervisord.py", line 281, in reap
    process.finish(pid, sts)
  File "/usr/lib/python3.11/site-packages/supervisor/process.py", line 585, in finish
    self.config.options.logger.warn(msg)
  File "/usr/lib/python3.11/site-packages/supervisor/loggers.py", line 331, in warn
    self.log(LevelsByName.WARN, msg, **kw)
  File "/usr/lib/python3.11/site-packages/supervisor/loggers.py", line 345, in log
    handler.emit(record)
  File "/usr/lib/python3.11/site-packages/supervisor/loggers.py", line 227, in emit
    self.doRollover()
  File "/usr/lib/python3.11/site-packages/supervisor/loggers.py", line 264, in doRollover
    if not (self.stream.tell() >= self.maxBytes):
            ^^^^^^^^^^^^^^^^^^
OSError: [Errno 29] Invalid seek
/docker-entrypoint.sh: Starting pre-launch ...
/docker-entrypoint.sh: Existing installation found!
redis (172.44.0.3:6379) open
db (172.44.0.2:3306) open
/docker-entrypoint.sh: Config preprocessing ...
/docker-entrypoint.sh: installation active
/docker-entrypoint.sh: debug disabled
/docker-entrypoint.d/50-humhub-validate.sh
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/50-humhub-validate.sh
validating ...
*** Performing database integrity checks
Validating: Mail Module (0 conversations)
Validating: Mail Module (0 message entries)
Validating: Mail Module (0 user message entries)
Validating: Mail Module (0 user message tag entries)
Validating: Polls Module - Answers (12 entries)
Validating: Polls Module - Answers User (0 entries)
Validating: External Calendar Module - Entries (0 entries)
Validating: ReportContent Module (0 entries)
Validating: Calendar Module (0 reminder entries)
Validating: Calendar Module (0 reminder sent entries)
Validating: HumHub DAV Access Module - Token (0 entries)
Validating: Activity Module (18 entries)
Validating: Space Module - Spaces (6 entries)
Validating: Space Module - Memberships (8 entries)
Validating: Notification Module (7 entries)
Validating: File Module (0 entries)
Validating: Post  Module - Posts (6 entries)
Validating: Like (0 entries)
Validating: User Module - ContentContainer (2 entries)
Validating: User Module - Users (2 entries)
Validating: User Module - Password (2 entries)
Validating: User Module - Profile (2 entries)
Validating: User Module - Mentioning (0 entries)
Validating: User Module - Follow (10 entries)
Validating: User Module - Content container (8 entries)
Validating: Content Objects (26 entries)
Validating: Comment Module (2 entries)
*** All integrity checks done
/docker-entrypoint.sh: Launching /docker-entrypoint.d/60-nginx-config.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/70-nginx-allowedips.sh
Setting HUMHUB_REVERSEPROXY_WHITELIST
Added 127.0.0.1 to Reverseproxy Whitelist
/docker-entrypoint.sh: Configuration complete; ready for start up
/docker-entrypoint.sh: Entrypoint finished! Launching ...
tail: can't open '/var/www/localhost/htdocs/protected/runtime/logs/app.log': No such file or directory
tail: no files
2024-03-05 10:13:30,584 WARN exited: humhub-log (exit status 1; not expected)
2024-03-05 10:13:30,584 WARN exited: humhub-log (exit status 1; not expected)
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 33, in <module>
    sys.exit(load_entry_point('supervisor==4.2.5', 'console_scripts', 'supervisord')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/supervisor/supervisord.py", line 359, in main
    go(options)
  File "/usr/lib/python3.11/site-packages/supervisor/supervisord.py", line 369, in go

    d.main()
  File "/usr/lib/python3.11/site-packages/supervisor/supervisord.py", line 78, in main
    self.run()
  File "/usr/lib/python3.11/site-packages/supervisor/supervisord.py", line 94, in run
    self.runforever()
  File "/usr/lib/python3.11/site-packages/supervisor/supervisord.py", line 244, in runforever
    self.reap()
  File "/usr/lib/python3.11/site-packages/supervisor/supervisord.py", line 281, in reap
    process.finish(pid, sts)
  File "/usr/lib/python3.11/site-packages/supervisor/process.py", line 585, in finish
    self.config.options.logger.warn(msg)
  File "/usr/lib/python3.11/site-packages/supervisor/loggers.py", line 331, in warn
    self.log(LevelsByName.WARN, msg, **kw)
  File "/usr/lib/python3.11/site-packages/supervisor/loggers.py", line 345, in log
    handler.emit(record)
  File "/usr/lib/python3.11/site-packages/supervisor/loggers.py", line 227, in emit
    self.doRollover()
  File "/usr/lib/python3.11/site-packages/supervisor/loggers.py", line 264, in doRollover
    if not (self.stream.tell() >= self.maxBytes):
            ^^^^^^^^^^^^^^^^^^
OSError: [Errno 29] Invalid seek`
